rifa/urls.py
from django.urls import path
from .views import *

app_name = 'siterifa'

urlpatterns = [
    path('', homepage, name='home'),
    path('rifa/<int:rifa_id>/', comprar, name='shop'),
    path('finalizar_pagamento/', finalizar_pagamento, name='finalizar_pagamento'),
    path('pix/', pix, name='pix'),
    path('aprovada/', compraaprovada, name='aprovada')
]

siterifa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rifa.urls', namespace='siterifa'))
]

rifa/models.py
from django.db import models

# Create your models here.


class Sorteio(models.Model):
    nome = models.CharField(max_length=100)
    sobrenome = models.CharField(max_length=100)
    numero_rifa = models.IntegerField()
    aprovado = models.BooleanField(default=False)


    def __str__(self):
        return self.nome
    
class RifaTexto(models.Model):
    texto = models.TextField()

    def __str__(self):
        return self.texto

rifa/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse
from django.urls import reverse
from .api_mercadopago import create_payment
from .models import Sorteio
from django.core.exceptions import PermissionDenied

def homepage(request):
    numeros = Sorteio.objects.filter(aprovado=True)
    numeros_bloqueados = [num.numero_rifa for num in numeros]
    return render(request, 'homepage.html', {'my_range': range(251), 'numeros_bloqueados': numeros_bloqueados})

def comprar(request, rifa_id):
    numeros = Sorteio.objects.filter(aprovado=True)
    numeros_bloqueados = [num.numero_rifa for num in numeros]
    if rifa_id in numeros_bloqueados or rifa_id >= 251:
        raise PermissionDenied
    else:
        if request.method == 'GET':
            return render(request, 'shop.html', {'rifa': rifa_id})
        elif request.method == 'POST':
            nome = request.POST.get('nome')
            sobrenome = request.POST.get('sobrenome')
            link = request.build_absolute_uri(reverse('siterifa:finalizar_pagamento') + f'?rifa_id={rifa_id}&nome={nome}&sobrenome={sobrenome}')
            link_pagamento, id_pagamento = create_payment(rifa_id, link)
            pagamento = Sorteio.objects.create(nome=nome, sobrenome=sobrenome, numero_rifa=rifa_id, aprovado=False)
            pagamento.save()
            return redirect(link_pagamento)

def compraaprovada(request):
    return render(request, 'agradecimento.html')

def pix(request):
    return render(request, 'pix.html')

def finalizar_pagamento(request):
    dados = request.GET.dict()
    status = dados.get('status')
    rifa_id = dados.get('rifa_id') 
    nome = dados.get('nome')
    sobrenome = dados.get('sobrenome')
    if status == 'approved':
        numero_escolhido = Sorteio.objects.get(numero_rifa=rifa_id)
        numero_escolhido.aprovado = True
        numero_escolhido.save()
        return redirect('siterifa:aprovada')

    elif status == 'rejected':
        numero_escolhido = Sorteio.objects.get(numero_rifa=rifa_id)
        numero_escolhido.delete()
        return redirect('siterifa:home')
    return redirect('siterifa:home')

templates/agradecimento.html
{% extends 'base.html' %}


{% load static %}

{% block body %}
<section>
    <img class="gratidao-emoji" src="{% static 'img/gratidao.png' %}">
    <h1 style="font-size: 20px;" class="h1-animate">Gratidão por você contribuir com a rifa</h1>
</section>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    {% load static %}
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/css.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'settings_mobile/media.css' %}">
    <script src="{% static 'script/app.js' %}"></script>
    {% endblock %}

    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    <header>
        {% include 'navbar.html' %}
    </header> 
    {% block body %}
    {% endblock %}
</body>
</html>

templates/homepage.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Rifa
{% endblock %}

{% block body %}
<section class="sec-1 show-animate">
    <img class="animate emoji-facu" src="{% static 'img/chapeu_facu.png' %}">
    <h1 class="animate h1-animate"><br>Rifa Formatura Gustavo Mundim
        <br>
        Curso Engenharia Agrônomica
        <p class="p-animate">Role para baixo</p>
    </h1>
</section>
<section class="sec-2">
    <img class="animate money-img" src="{% static 'img/money.png' %}">
    <h1 class="animate h1-animate">Contribua com R$ 10,00
    </h1>
</section>
<section class="sec-3">
    <h1 class="alexa-text">E concorra a uma Alexa Echo Dot 5ª geração</h1>
    <div class="border-pix bg-white shadow border border-Black-5 rounded-2xl max-w-2xl flex flex-col gap-[2px] mx-auto mt-[16px] p-[24px]">
    <img src="{% static 'img/alexa.jpg' %}" class="alexa-dot animate">
</div>
<br>
<h1 style="font-size: 10px" class="alexa-text">O sorteio será realizado quando todos numeros forem vendidos</h1>
</section>

<section class="sec-4">
    <img class="animate sorteio-image" src="{% static 'img/sorteio.png' %}">
    <h1 class="animate h1-animate">
        Escolha seu numero abaixo
    </h1>
</section>

<section>
    <div class="container space-y-2 sm:space-y-7">
        {% for i in my_range %}
            {% if i in numeros_bloqueados %}
            <button class="rounded-full bg-red-600 px-4 py-1 hover:bg-red-600 btn-on">{{ i }}</button>
            {% else %}
            <button class="rounded-full bg-green-600 px-4 py-1 hover:bg-red-600 btn-on" onclick="sorteio({{i}}, this)">{{ i }}</button>
            {% endif %}
        {% endfor %}
    </div>
</section>


<script>
    function sorteio(id, button) {
        var url = '/rifa/' + id;
        window.location.href = url;
    }
</script>
{% endblock %}

templates/pix.html
{% extends 'base.html' %}

{% load static %}

{% block body %}
<section>
<div class="border-pix bg-white shadow border border-Black-5 rounded-2xl max-w-2xl flex flex-col gap-[2px] mx-auto mt-[16px] p-[24px]">
    <p class="flex gap-2 items-center text-sm sm:text-base"><span class="shadow text-sm bg-green-500 w-6 flex-none h-6 flex rounded-full items-center justify-center text-white">1</span>Copie a chave PIX. </p>
    <p class="flex gap-2 items-center text-sm sm:text-base"><span class="shadow text-sm bg-green-500 w-6 flex-none h-6 flex rounded-full items-center justify-center text-white">2</span> Abra o aplicativo do seu banco e escolha a opção . </p>
    <p class="flex gap-2 items-center text-sm sm:text-base"><span class="shadow text-sm bg-green-500 w-6 flex-none h-6 flex rounded-full items-center justify-center text-white">3</span> Efetue o pagamento e me mande o comprovante via whatsaap com o numero da rifa junto com nome e sobrenome</p>
    <div class="cursor-pointer relative mt-[16px]">
        <input type="text" required class="cursor-pointer bg-white border border-Black-100 pl-[14px] pr-[70px] py-[12px] rounded-lg w-full" value="00020126580014BR.GOV.BCB.PIX0136154a73c7-333e-48d4-9c55-f51f09c935bb520400005303986540510.005802BR5921Gustavo Borges Mundim6009SAO PAULO62140510BHcu5IiSxP6304DB1C">
        <button type="button" class="copy-button absolute top-1/2 -translate-y-1/2 right-4 text-sm flex gap-[8px] items-center">Copiar</button>
    </div>
    <div class="text-center mt-[16px]">
      <p>OU</p>
      <p>ESCANEIE ESSE QRCODE</p>
    </div>
    <a href="https://api.whatsapp.com/send/?phone=5534997724983&text&type=phone_number&app_absent=0"><img class="logo-whats" src="{% static 'img/whatsaap.png' %}"></a>
    <img src="{% static 'img/qrcodenu.jpg' %}" class="border border-Black-5 mx-auto rounded-2xl h-46 w-48 shadow mt-[16px]">
  </div>
</section>
<script>
    let copyButton = document.querySelector('.copy-button');
    copyButton.addEventListener('click', function(){
        let input = document.querySelector('input[type="text"]');
        input.select();
        document.execCommand('copy');
    });
</script>
{% endblock %}

templates/shop.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<section class="rifa">
    <!-- <div class="container-qrcode bg-white shadow border border-Black-5 rounded-2xl max-w-2xl flex flex-col gap-[8px] mx-auto mt-[16px] p-[24px]">
    </div> -->
    <form class="container-adjust w-full max-w-lg" method="POST" action="">{% csrf_token %}
        <div class="numero-rifa">
           N°: {{rifa}}
        </div>
        <div class="flex flex-wrap -mx-3 mb-6">
          <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
            <label id='nome' class=" block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">
              Nome
            </label>
            <input class="input-nome appearance-none block w-full bg-gray-200 text-gray-700 border border-red-500 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="grid-first-name" type="text" placeholder="Jane" name="nome">
            <p class="aviso-campo text-red-500 text-xs italic">Por favor insira os dados em todos campos</p>
          </div>
          <div class="w-full md:w-1/2 px-3">
            <label id="sobrenome" class=" block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-last-name">
              Sobrenome
            </label>
            <input class="input-sobrenome appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-last-name" type="text" placeholder="Doe" name="sobrenome">
          </div>
        </div>
        <a href="{% url 'siterifa:pix' %}" class="aviso-whats rounded-md bg-green-600 py-2">Caso queira fazer por PIX clique aqui</a>
        <div class="flex justify-end">
          <button type="submit" class="button-send bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            Enviar
          </button>
        </div>
    </form>
</section>

{% endblock %}